drop database DETRAN;
CREATE DATABASE IF NOT EXISTS DETRAN;  
USE DETRAN;  

CREATE TABLE PROPIETARIO (  
    CPF CHAR(14) PRIMARY KEY,  
    Nome VARCHAR(100) NOT NULL,  
    Data_Nascimento DATE NOT NULL,  
    CEP CHAR(9) NOT NULL,  
    Numero_Complemento VARCHAR(20),  
    Sexo CHAR(1),  
    Bairro VARCHAR(50),  
    Cidade VARCHAR(50),  
    Estado CHAR(2)  
) ENGINE=InnoDB;  

CREATE TABLE TELEFONE (  
    FK_PROPIETARIO_CPF CHAR(14) NOT NULL,  
    Numero CHAR(11) NOT NULL,  
    PRIMARY KEY (FK_PROPIETARIO_CPF, Numero),  
    FOREIGN KEY (FK_PROPIETARIO_CPF) REFERENCES PROPIETARIO(CPF)  
) ENGINE=InnoDB;  

CREATE TABLE MODELO (  
    ID_MODELO INT(6) ZEROFILL PRIMARY KEY AUTO_INCREMENT,  
    Nome VARCHAR(100) NOT NULL  
) ENGINE=InnoDB;  

CREATE TABLE CATEGORIA (  
    ID_Categoria INT(2) ZEROFILL PRIMARY KEY AUTO_INCREMENT,  
    Nome VARCHAR(100) NOT NULL  
) ENGINE=InnoDB;  

CREATE TABLE VEICULO (  
    Placa CHAR(8) PRIMARY KEY,  
    Chassi CHAR(17) UNIQUE NOT NULL,  
    Cor VARCHAR(15) NOT NULL,  
    Ano_Fabricacao YEAR NOT NULL,  
    FK_PROPIETARIO_CPF CHAR(14) NOT NULL,  
    FK_MODELO_ID INT(6) ZEROFILL NOT NULL,  
    FK_CATEGORIA_ID INT(2) ZEROFILL NOT NULL,  
    FOREIGN KEY (FK_PROPIETARIO_CPF) REFERENCES PROPIETARIO(CPF),  
    FOREIGN KEY (FK_MODELO_ID) REFERENCES MODELO(ID_MODELO),  
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID_Categoria)  
) ENGINE=InnoDB;  

CREATE TABLE AGENTE (  
    Matricula INT PRIMARY KEY,  
    Nome VARCHAR(100) NOT NULL,  
    Data_Contratacao DATE NOT NULL  
) ENGINE=InnoDB;  
 
CREATE TABLE TIPO_INFRACAO (  
    ID_Tipo INT PRIMARY KEY AUTO_INCREMENT,  
    Descricao VARCHAR(100) NOT NULL,  
    Valor DECIMAL(10,2) NOT NULL  
) ENGINE=InnoDB;  

CREATE TABLE LOCAL (  
    Latitude DECIMAL(9,6) NOT NULL,  
    Longitude DECIMAL(9,6) NOT NULL,  
    Velocidade_Permitida DECIMAL(5,2) NOT NULL,  
    PRIMARY KEY (Latitude, Longitude)  
) ENGINE=InnoDB;  

CREATE TABLE INFRACAO (  
    ID_Infracao INT PRIMARY KEY AUTO_INCREMENT,  
    Data_Hora DATETIME NOT NULL,  
    Velocidade_Aferida DECIMAL(5,2),  
    FK_AGENTE_Matricula INT NOT NULL,  
    FK_LOCAL_Latitude DECIMAL(9,6) NOT NULL,  
    FK_LOCAL_Longitude DECIMAL(9,6) NOT NULL,  
    FK_TIPO_INFRACAO_ID_Tipo INT NOT NULL,  
    FK_VEICULO_Placa CHAR(8) NOT NULL,  
    FOREIGN KEY (FK_AGENTE_Matricula) REFERENCES AGENTE(Matricula),  
    FOREIGN KEY (FK_LOCAL_Latitude, FK_LOCAL_Longitude) REFERENCES LOCAL(Latitude, Longitude),  
    FOREIGN KEY (FK_TIPO_INFRACAO_ID_Tipo) REFERENCES TIPO_INFRACAO(ID_Tipo),  
    FOREIGN KEY (FK_VEICULO_Placa) REFERENCES VEICULO(Placa)  
) ENGINE=InnoDB;  